// =========================
// LOCATIONS
// =========================

const locations = [
"Starter Pokemon",
"Aspertia City",
"Route 19",
"Floccesy Town",
"Route 20",
"Floccesy Ranch",
"Virbank City",
"Virbank Complex",
"Castelia City",
"Castelia Sewers",
"Relic Passage",
"Route 4",
"Desert Resort",
"Relic Castle",
"Route 16",
"Lostlorn Forest",
"Route 5",
"Route 5 - Hidden Grotto",
"Driftveil Drawbridge",
"Driftveil City",
"Route 6",
"Mistralton Cave",
"Chargestone Cave",
"Route 7",
"Celestial Tower",
"Reversal Tower",
"Strange House",
"Undella Town",
"Undella Bay",
"Undella Bay - Static",
"Route 13",
"Route 12",
"Village Bridge",
"Route 11",
"Route 9",
"Seaside Cave",
"Route 21",
"Humilau City",
"Route 22",
"Giant Chasm",
"Route 23",
"Victory Road",
"Marvelous Bridge",
"Route 15",
"Route 14",
"Abundant Shrine",
"Moor of Icirrus",
"Icirrus City",
"Dragonspiral Tower",
"Twist Mountain",
"Clay Tunnel",
"Underground Ruins",
"Pinwheel Forest",
"Nacrene City",
"Route 3",
"Wellspring Cave",
"Striaton City",
"Dreamyard",
"Accumula Town",
"Route 1",
"Route 17",
"Route 18",
"P2 Laboratory",
"Nature Preserve",
"Free Slot 1",
"Free Slot 2",
"Free Slot 3",
"Free Slot 4",
"Free Slot 5",
"Free Slot 6",
"Free Slot 7",
"Free Slot 8",
"Free Slot 9",
"Free Slot 10",
];